name: Version

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Choose which type of release to perform.
        options: [ major, minor, patch ]
        default: patch

jobs:

  version:
    name: Update VERSION File
    runs-on: ubuntu-latest
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Create Release Commit
        run: |
          version=$(cat VERSION)
          echo "CURRENT_VERSION: '${version}'"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$version"
        
          if [[ "${{ github.event.inputs.release_type }}" == "major" ]]; then
              NEW_VERSION="$((MAJOR+1)).0.0"
          elif [[ "${{ github.event.inputs.release_type }}" == "minor" ]]; then
              NEW_VERSION="${MAJOR}.$((MINOR+1)).0"
          else
              NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH+1))"
          fi
        
          echo "NEW_VERSION='${NEW_VERSION}'"
          echo "new_ver=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "$NEW_VERSION" > "VERSION"
        
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION
          git commit -m "${{ vars.NAME }} Release ${NEW_VERSION}"
          git push origin master

